{"timestamp":"2025-10-26T07:21:24.475017Z","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager","filename":"manager.py","lineno":179}
{"timestamp":"2025-10-26T07:21:24.477112Z","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/etl_dag_from_scripts.py","logger":"airflow.models.dagbag.DagBag","filename":"dagbag.py","lineno":593}
{"timestamp":"2025-10-26T07:21:24.577952Z","level":"info","event":"Task instance is in running state","logger":"task.stdout"}
{"timestamp":"2025-10-26T07:21:24.581432Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","logger":"task.stdout"}
{"timestamp":"2025-10-26T07:21:24.582024Z","level":"info","event":"Current task name:run_etl_process","logger":"task.stdout"}
{"timestamp":"2025-10-26T07:21:24.582395Z","level":"info","event":"Dag name:etl_retail_transactions_dag","logger":"task.stdout"}
{"timestamp":"2025-10-26T07:21:24.583145Z","level":"info","event":"Starting ETL Process","logger":"task.stdout"}
{"timestamp":"2025-10-26T07:21:24.583561Z","level":"info","event":"Extracting data from source_db...","logger":"task.stdout"}
{"timestamp":"2025-10-26T07:21:24.600014Z","level":"error","event":"Task failed with exception","logger":"task","filename":"task_runner.py","lineno":972,"error_detail":[{"exc_type":"AirflowNotFoundException","exc_value":"The conn_id `postgres_local` isn't defined","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1307,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":416,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":82,"name":"run"},{"filename":"/opt/airflow/dags/etl_dag_from_scripts.py","lineno":19,"name":"etl_process"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py","lineno":234,"name":"get_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py","lineno":243,"name":"connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/hook.py","lineno":61,"name":"get_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/definitions/connection.py","lineno":228,"name":"get"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/definitions/connection.py","lineno":218,"name":"_handle_connection_error"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-10-26T07:21:24.635031Z","level":"info","event":"Task instance in failure state","logger":"task.stdout"}
{"timestamp":"2025-10-26T07:21:24.636086Z","level":"info","event":"Task start","logger":"task.stdout"}
{"timestamp":"2025-10-26T07:21:24.636778Z","level":"info","event":"Task:<Task(PythonOperator): run_etl_process>","logger":"task.stdout"}
{"timestamp":"2025-10-26T07:21:24.637536Z","level":"info","event":"Failure caused by The conn_id `postgres_local` isn't defined","logger":"task.stdout"}
